# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Debian package

on:
  push:
    branches: [ github-actions-* ]
#  pull_request:
#    branches: [ main ]

#on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18 for x64
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18'
        java-package: jdk+fx
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Copy jar to deb 
      run: mkdir jar && cp shade/*.jar jar
    - name: Package jar as deb
      run: jpackage --input jar --main-jar LATIC-1.2.1.jar --name LATIC --description "LATIC - A Linguistic Analyzer for Text and Item Characteristics" --vendor "Florian Klückmann" --linux-menu-group Office --linux-shortcut --icon ./src/main/resources/software/latic/latic-square-256.png --linux-deb-maintainer hello@latic.software -d deb --app-version 1.2.1
    - uses: actions/upload-artifact@v2
      with: 
        name: LATIC-1.2.1-Ubuntu-Debian-EN-DE
        path: deb/*
