# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: macOs package

on:
  push:
    branches: [ github-actions-* ]
#  pull_request:
#    branches: [ main ]

#on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18 for x64
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18'
        java-package: jdk+fx
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Copy jar
      run: mkdir jar && cp shade/*.jar jar
    - name: Package jar as pkg
      run: jpackage --input jar --main-jar LATIC-1.2.1.jar --name LATIC --description "LATIC - A Linguistic Analyzer for Text and Item Characteristics" --vendor "Florian Klückmann" --icon ./src/main/resources/software/latic/latic-square-256.png -d pkg --app-version 1.2.1 --mac-package-identifier LATIC --mac-package-name LATIC --type pkg
    - uses: actions/upload-artifact@v2
      with: 
        name: LATIC-1.2.1-macOS-EN-DE
        path: pkg/*
