# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Debian package

on:
#  push:
#    branches: [ github-actions-* ]
#  pull_request:
#    branches: [ main ]

#on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Java version
      run: echo java_version=$(mvn help:evaluate -Dexpression=javafx.version -q -DforceStdout) >> $GITHUB_ENV
    - name: Set up JDK ${{ env.java_version }} for x64
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ env.java_version }}
        java-package: jdk+fx
        architecture: x64
    - name: Get version
      run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
    - name: test
      run: echo test ${{ env.project_version }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml -P en-de,all-lang
    - name: Copy jar to deb 
      run: mkdir jar && cp shade/*.jar jar
    - name: Get version
      run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
    - name: Package jar as deb
      run: jpackage --input jar --main-jar LATIC-${{ env.project_version }}.jar --name LATIC --description "LATIC - A Linguistic Analyzer for Text and Item Characteristics" --vendor "Florian Klückmann" --linux-menu-group Office --linux-shortcut --icon ./src/main/resources/software/latic/latic-square-256.png --linux-deb-maintainer hello@latic.software -d deb --app-version ${{ env.project_version }} --license-file ./LICENSE --linux-rpm-license-type GPL-3.0-or-later --about-url https://www.latic.software
    - name: Copy documentation and installation guide
      run: | 
        mkdir deb/english
        mkdir deb/deutsch
        cp ./src/main/resources/software/latic/documentation_en.pdf "deb/english/LATIC ${{ env.project_version }} Documentation.pdf"
        cp ./src/main/resources/software/latic/documentation_de.pdf "deb/deutsch/LATIC ${{ env.project_version }} Dokumentation.pdf"
        cp "./supplemental-material/en/Instructions Installing and Starting LATIC on Ubuntu and Debian.docx" "deb/english/Instructions Installing and Starting LATIC on Ubuntu and Debian.docx"
        cp "./supplemental-material/de/Anleitung LATIC installieren und starten Ubuntu und Debian.docx" "deb/deutsch/Anleitung LATIC installieren und starten Ubuntu und Debian.docx"
    - uses: actions/upload-artifact@v2
      with: 
        name: LATIC-${{ env.project_version }}-Ubuntu-Debian-all-lang
        path: deb/*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK ${{ env.java_version }} for x64
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.java_version }}
          java-package: jdk
          architecture: x64
      - uses: actions/checkout@v3
      - name: Get version
        run: echo project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
      - name: Download artifacts for build
        uses: actions/download-artifact@v3
        with:
          name: LATIC-${{ env.project_version }}-Ubuntu-Debian-all-lang
          path: LATIC-${{ env.project_version }}-Ubuntu-Debian-all-lang
      - name: Display structure of downloaded files
        run: ls -R
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'LATIC-${{ env.project_version }}-Ubuntu-Debian-all-lang.zip'
          path: LATIC-${{ env.project_version }}-Ubuntu-Debian-all-lang
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: LATIC-${{ env.project_version }}-Ubuntu-Debian-all-lang.zip